### ISSUE TITLE
manager启动报错

### ISSUE THREAD

**Issue by lybc** [Hlianfa/heimdallr-sdk#14]
node_modules/vite/dist/node/chunks/dep-40c65ceb.js:40970:10: ERROR: [plugin: vite:dep-scan] Failed to resolve entry for package "type-json-mapper". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "type-json-mapper". The package may have incorrect main/module/exports specified in its package.json.

vite 和 nodejs版本
vite/2.9.17 darwin-x64 node-v16.15.0

**Comment by LucivHuang** [comment]
已修复，删除 node_modules，重新安装一下依赖
