### ISSUE TITLE
在项目里使用 project/init 接口404

### ISSUE THREAD

**Issue by lxy030988** [Hlianfa/heimdallr-sdk#17]
![2024-05-15_140232](https://github.com/LuciferHua
![2024-05-15_140347](https://github.com/LuciferHuang/heimdallr-sdk/assets/29250746/6247d274-1ec6-4121-aabd-276b63bc7409)
ng/heimdallr-sdk/assets/29250746/dfb70042-ff0a-4e15-82ca-4cfa9a85056a)
![2024-05-15_140328](https://github.com/LuciferHuang/heimdallr-sdk/assets/29250746/e0737ea7-4d67-4971-bfe9-bfd05f119343)

**Comment by lxy030988** [comment]
![2024-05-15_140232](https://github.com/LuciferHuang/heimdallr-sdk/assets/29250746/d718ad09-a27f-4ec6-a5ea-a9885f1af28b)

**Comment by lxy030988** [comment]
本地启动的项目，在自己环境里通过npm方式引入了，发现初始化接口404

![2024-05-15_140619](https://github.com/LuciferHuang/heimdallr-sdk/assets/29250746/d8d80a15-7181-4a4d-84b3-79bc092919f6)

**Comment by LucivHuang** [comment]
@lxy030988 后端服务用的是 @heimdallr-sdk/server 项目吗？

**Comment by lxy030988** [comment]
@LuciferHuang 是的 项目拉下来 直接本地启动的 看其他接口 都有的

**Comment by lxy030988** [comment]
我用@heimdallr-sdk/cli 把 前端 后端 代码 单独拉下来 ，可以跑了。但是 用 @heimdallr-sdk/record  upload 接口 会报错

**Comment by lxy030988** [comment]
![image](https://github.com/LuciferHuang/heimdallr-sdk/assets/29250746/636e5987-634b-41dd-b036-239a7f5b9278)
![image](https://github.com/LuciferHuang/heimdallr-sdk/assets/29250746/728f1eeb-adc0-4499-a244-1031075ba77c)

**Comment by lxy030988** [comment]
Unexpected token \u0011 in JSON at position 1877

session not found

**Comment by LucivHuang** [comment]
问题已修复，获取一下最新版本，如有其他问题再另提单吧
