### ISSUE TITLE
引入@heimdallr-sdk/record 后rrweb库报警告

### ISSUE THREAD

**Issue by 947291135** [Hlianfa/heimdallr-sdk#20]
Module not found: Error: Can't resolve 'worker_threads'

官方已经修复了该版本，请更新版本号
![Uploading image.png…]()

**Comment by LucivHuang** [comment]
图片丢了，重新上传一下吧

**Comment by LucivHuang** [comment]
太长时间未回复，暂时关闭。如还有疑问，欢迎提新的 issue
