### ISSUE TITLE
引入@heimdallr-sdk/record 后上报数据 server端报错msg :  "paramData.replace is not a function"

### ISSUE THREAD

**Issue by 947291135** [Hlianfa/heimdallr-sdk#21]
![image](https://github.com/LuciferHuang/heimdallr-sdk/assets/26854734/6a3b7ff6-8f34-4694-99e0-7a106f8bb88c)
传递的dat 为数组，但是在上报主逻辑的uploadCtrl方法中却使用了paramData.replace方法

**Comment by 947291135** [comment]
![image](https://github.com/LuciferHuang/heimdallr-sdk/assets/26854734/044b1530-59a2-4eb4-9701-29e8edc1c2f2)
JSON.stringify包裹住一层后server端继续报错\nInvalid `this.prisma.log.createMany()` 
![image](https://github.com/LuciferHuang/heimdallr-sdk/assets/26854734/6285e44c-f661-4430-84ea-0365a67d82c8)

**Comment by LucivHuang** [comment]
> ![image](https://private-user-images.githubusercontent.com/26854734/344953528-6a3b7ff6-8f34-4694-99e0-7a106f8bb88c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MzA4ODksIm5iZiI6MTcxOTkzMDU4OSwicGF0aCI6Ii8yNjg1NDczNC8zNDQ5NTM1MjgtNmEzYjdmZjYtOGYzNC00Njk0LTk5ZTAtN2ExMDZmOGJiODhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDE0Mjk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NmVhZDgwMzE5NDk0OTUyZTZmZTMwMmQ1YzgxZDE1MGIwM2YxMGUyZWNkYjNjOWNmYzU0OWViYWI2OTg1ZjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QvpZ12tkBX8P-hT01kwYroWu_gCndoGRExvZXQPB1o8) 传递的dat 为数组，但是在上报主逻辑的uploadCtrl方法中却使用了paramData.replace方法

默认使用 beacon 上报，paramData 就是 string 类型的。修改了上报方式吗？

**Comment by LucivHuang** [comment]
> ![image](https://private-user-images.githubusercontent.com/26854734/344956191-044b1530-59a2-4eb4-9701-29e8edc1c2f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MzA4ODksIm5iZiI6MTcxOTkzMDU4OSwicGF0aCI6Ii8yNjg1NDczNC8zNDQ5NTYxOTEtMDQ0YjE1MzAtNTlhMi00ZWI0LTk3MDEtMjllOGVkYzFjMmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDE0Mjk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZGI2ZTY0ZjIxMWRhNmE1OWVhMjRmNTJhZTE0YjJkNzQyZGNjZjUwYzM1OWI5OTg1ODBiOGRlYmU2N2VlNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GV3vX50YYHPbSvTmgrO91vpgB1nNzTRYbO6TZoOnSLo) JSON.stringify包裹住一层后server端继续报错\nInvalid `this.prisma.log.createMany()` ![image](https://private-user-images.githubusercontent.com/26854734/344956424-6285e44c-f661-4430-84ea-0365a67d82c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MzA4ODksIm5iZiI6MTcxOTkzMDU4OSwicGF0aCI6Ii8yNjg1NDczNC8zNDQ5NTY0MjQtNjI4NWU0NGMtZjY2MS00NDMwLTg0ZWEtMDM2NWE2N2Q4MmM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDE0Mjk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3MzExZWNhOWM4MWVkM2I0NzE5MzNlODhiYzMxZjAwZDdkY2VhM2U3NTFiZTdhYTk3MjFjNjNmOTU2NWEzNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9Bydip1UKhdy0s7Sxfz30o8U0OAGcb8pZspJKpH-fqY)

提供一下更详细的信息

**Comment by LucivHuang** [comment]
太长时间未回复，暂时关闭。如还有疑问，欢迎提新的 issue
