### ISSUE TITLE
position拼写错误

### ISSUE THREAD

**Issue by metogo** [Hlianfa/heimdallr-sdk#23]
https://luciferhuang.github.io/heimdallr-sdk/usage/browser.html

import heimdallr from "@heimdallr-sdk/browser";
heimdallr({
    dsn: {
        host: 'localhost:8888',
        init: '/project/init',
        report: '/log/report'
    },
    app: {
        name: 'playgroundAPP',
        leader: 'test',
        desc: 'test proj'
    },
    userIdentify: {
        name: '__state__.a.0.user.id', // window.__state__ = { a: [{ user: { id:'123' } }] }
        position: 'global'
    }
});

position: 'global'    应为：postion

**Comment by yby1999** [comment]
我也发现了

**Comment by LucivHuang** [comment]
最新版本已统一修改为 “position”，欢迎更新使用
