### ISSUE TITLE
Error: Cannot find module './lib/utils'  

### ISSUE THREAD

**Issue by guyuessl** [Hlianfa/heimdallr-sdk#25]
博主，脚手架创建时，heimdallr-create，提示这个 Error: Cannot find module './lib/utils'  ，

**Comment by LuciferHuang** [comment]
问题已修复，获取最新版本再试一下

**Comment by LucivHuang** [comment]
问题已修复，获取最新版 @heimdallr-sdk/cli 再尝试一下

**Comment by guyuessl** [comment]
好的
