### ISSUE TITLE
监听错误有问题吗？

### ISSUE THREAD

**Issue by twosSign** [Hlianfa/heimdallr-sdk#3]
在浏览器端监听的时候，浏览器打印出错误来，但是项目日志没监听到错误

**Comment by twosSign** [comment]
是服务器端这个报错的影响吗？
src\models\sessionModel.ts:11:48

   8 }
   9 async add(datas: Session[]): Promise<ModelResponseType<Session>> {
  10   try {
→ 11     const result = await this.prisma.session.createMany({
           data: [
             {
               id: '6666c322-8da9-43d3-b243-61a60f46b0b2',
               user_id: '',
               ip: '::ffff:192.168.16.100',
               province: '',
               path: 'http://localhost:8080/waterDigitalMap/',
               page_title: '贵州省三维数字底图',
               stay_time: 0,
               terminal: 'pc',
               language: 'zh-CN',
               etime: '2023-4-12 17:16:40',
               ltime: '',
               events: '',
               ~~~~~~
               platform: 'browser'
             }
           ]
         })

Unknown arg `events` in data.0.events for type SessionCreateManyInput. Did you mean `select`? Available args:
type SessionCreateManyInput {
  id: String
  user_id: String
  ip: String
  province: String
  path: String
  page_title: String
  platform: String
  stay_time: Int
  terminal: String
  language: String
  etime: String
  ltime: String
  ctime?: DateTime
}

**Comment by LucivHuang** [comment]
尝试使用最新的脚手架部署，@heimdallr-sdk/cli@0.0.15
