### ISSUE TITLE
脚手架搭建heimdallr_client、heimdallr_server

### ISSUE THREAD

**Issue by panyulong** [Hlianfa/heimdallr-sdk#5]
不知道重启那个项目后，之前的所有监控到的信息都丢失了

**Comment by LucivHuang** [comment]
执行了 prisma 命令吗？执行 prisma 命令后，如果表结构有变更，是会询问是否清空之前的数据的，可以留意一下命令行提示

**Comment by panyulong** [comment]
<img width="668" alt="1681377086019" src="https://user-images.githubusercontent.com/30285932/231712480-20af83b1-b6a5-4e2d-961e-2ffb7e9b2fb4.png">
日志管理里这种接口异常能捕获得到地址和返回值
