### ISSUE TITLE
React umi项目录屏上报请求连接被取消

### ISSUE THREAD

**Issue by zt6666397** [Hlianfa/heimdallr-sdk#7]
leave能上报，录屏无法上报请求连接被取消

**Comment by zt6666397** [comment]
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/65266015/233310392-ba0434de-189a-405c-8fc8-5ac9f7cd5f33.png">

**Comment by LucivHuang** [comment]
录屏数据量过大，上报接口被取消了，0.0.13版本已解决 [[9a5f9e1]](https://github.com/LuciferHuang/heimdallr-sdk/commit/9a5f9e129569b2fe937a32c4f631d9c3f30fe0ca)
