### ISSUE TITLE
yarn run build 报错

### ISSUE THREAD

**Issue by hitao123** [Hlianfa/heimdallr-sdk#8]
yarn  run dev 卡在下面

<img width="956" alt="image" src="https://github.com/LuciferHuang/heimdallr-sdk/assets/16607714/e8eea331-5333-49f5-84dd-a2496cd44c7c">

yarn run build

<img width="1094" alt="image" src="https://github.com/LuciferHuang/heimdallr-sdk/assets/16607714/13083301-5d73-41ba-ab0c-418110991ae7">

node 版本 v16.16.0
yarn 1.22.19
system macos

**Comment by LucivHuang** [comment]
1. 看你截图的部分没啥问题，你修改个文件保存试试，会重新编译的
2. 是 bug，已修复，拉一下最新的代码

**Comment by hitao123** [comment]
> 1. 看你截图的部分没啥问题，你修改个文件保存试试，会重新编译的
> 2. 是 bug，已修复，拉一下最新的代码

重新拉代码，build 正常了，顶大佬

**Comment by hitao123** [comment]
还有一个问题，本地跑 playground , vite 跑起来后少了一个类型，但是打包里面的文件夹是有这个 枚举类型的，好奇怪
<img width="1682" alt="image" src="https://github.com/LuciferHuang/heimdallr-sdk/assets/16607714/e6baa1d8-dd1b-4d98-977e-6d907ec0bcca">
<img width="1499" alt="image" src="https://github.com/LuciferHuang/heimdallr-sdk/assets/16607714/629e72e1-18c0-4dac-af44-3917d1910c06">
<img width="1383" alt="image" src="https://github.com/LuciferHuang/heimdallr-sdk/assets/16607714/926f03a2-15d5-4428-be49-e46157d79a8b">

**Comment by LucivHuang** [comment]
引用的有问题，拉下最新的代码。修复了已知问题，但是也改了插件引用方式，可以看看插件的 Readme

**Comment by hitao123** [comment]
> 

感谢
